:docinfo: shared
:toc: left
:toclevels: 5
:icons: font
:book:
:source-highlighter: rouge
:favicon: ./sample/favicon.png

= Tiny 🧸

Welcome to the documentation for `🧸 Tiny`, the virtual console that offers an easy and efficient way to build games and other applications with its Lua programming support, hot reloading, and 256-color maximum.

== Tiny Engine

Despite its modest capabilities, `🧸 Tiny` is designed to help you create and test your ideas quickly and effectively. Not only can you run your games on your desktop computer, but you can also export them for the web, making it easy to share your creations with others.

With `🧸 Tiny`, you'll be able to get started right away and see your progress in real-time, thanks to its hot reloading feature. This documentation will guide you through the setup and usage of `🧸 Tiny` as well as provide you with helpful tips and tricks to make the most out of this powerful tool.

> _Let's get started and unleash your creativity!_

++++
<iframe class="no-resize" title="Breakout example" width="536" height="536" src="sample/index.html"></iframe>
++++

NOTE: The code source of this sample is available in the https://github.com/minigdx/tiny/tree/main/tiny-sample[Tiny git repository].

== Tiny Sandbox

You can try to create a game right away `🧸 Tiny` using link:sandbox.html?game=[the Sandbox] or you can just try it by updating examples available in this page.

== Tiny is open source

`🧸 Tiny` is an open-source project. Users can contribute to the project by reporting issues, suggesting improvements, and even submitting code changes. https://github.com/minigdx/tiny[Check the code source on Github].

Contributions from the community are welcome, and can help to improve the overall functionality and usability of the game engine!

TIP: You can improve this documentation by updating https://github.com/minigdx/tiny/tree/main/tiny-doc/src/docs/asciidoc[the code of this documentation]

include::tiny-install.adoc[]

include::tiny-tutorial.adoc[]

include::tiny-showcase.adoc[]

include::tiny-cli.adoc[]

include::dependencies/tiny-api.adoc[]
