== Tiny CLI

Introducing the Tiny CLI, a powerful command-line interface that allows you to easily create, run, develop, and export games using the Tiny 2D game engine. With the Tiny CLI, you can quickly and easily create a new game project, add assets, and start developing your game in no time.

To get started, simply install the Tiny CLI on your system and create a new project using the `tiny create` command. This will generate a new project directory with all the necessary files and folder structure to start building your game. You can then add assets to your game using the `tiny add` command, which allows you to import images, audio files, and other resources into your project.

The Tiny CLI also includes a powerful development server that allows you to preview your game in real-time as you develop it. Simply run the tiny command and start to update your game.

When you're ready to share your game with the world, the Tiny CLI makes it easy to export your game for web browsers. You can use the `tiny export` command to generate a distributable version of your game that can be published on the web. You can also try the `export` result by using the command `tiny serve`.

Whether you're a seasoned game developer or just getting started, the Tiny CLI is a powerful tool that can help you create, run, develop, and export amazing 2D games with the Tiny engine. With its intuitive command-line interface and powerful features, the Tiny CLI is the ultimate tool for building your next great game.

=== tiny create
// TODO: Create a game

=== tiny
// TODO: Run the game

=== tiny add
// TODO: Add a resource into _tiny.json

=== tiny export
// TODO: Export the game as zip

=== tiny serve

The tiny serve command is used to launch a local web server that allows you to test a game that has been exported using the tiny export command. This is useful for testing and debugging a game locally before publishing it online.

==== Syntax

To use the tiny serve command, open a terminal or command prompt and navigate to the directory containing the exported game zip file. Then, type the following command:

```bash
tiny serve [options] game.zip
```

Where:

`[options]`: Optional arguments to modify the behavior of the command.
`game.zip`: The path to the exported game zip file.

===== Options

`--port [port number]`: Allows you to specify a custom port number to run the server on. The default port number is 8080.

==== Example Usage

To run the tiny serve command, you can use the following examples:

```bash
tiny serve myGame.zip
```

This will launch the local web server on the default port number (`8080`) and serve the game located in the `myGame.zip` file.

```bash
tiny serve MyGame.zip --port 8081
```

This will launch the local web server on port number `8081` and serve the game located in the `MyGame.zip` file.

Once the server is running, you can access the game in your web browser by navigating to the URL `http://localhost:[port number]/`. For example, if you used the default port number, you would navigate to `http://localhost:8080/` in your web browser to access the game.

NOTE: The tiny serve command is intended for local testing only and should not be used to serve your game online. When you are ready to publish your game, you should upload the exported game files to a web server and serve them from there.
